<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;

    protected $table = 'user_data';

    protected $fillable = [
        "free_user_id",
        "is_approve_ready",
        "temple_id",
        "lead_id",
        "extra_lead_id",
        "backup_lead_id",
        "org_lead_id",
        "name",
        "gender",
        "mobile_profile",
        "new_mobile_freeUser",
        "new_mobile_leadFamily",
        "age_freeUser",
        "sent_profiles_freeUser",
        "photo",
        "photo_score",
        "profiles_sent",
        "birth_place",
        "birth_date",
        "birth_time",
        "weight",
        "height",
        "height_int",
        "education",
        "degree",
        "college",
        "occupation",
        "profession",
        "working_city",
        "disability",
        "food_choice",
        "manglik",
        "monthly_income",
        "marital_status",
        "office_address",
        "about",
        "disabled_part",
        "abroad",
        "wantBot",
        "carousel",
        "company",
        "additional_qualification",
        "bot_language",
        "fcm_id",
        "bot_status",
        "last_seen",
        "fcm_app",
        "education_score",
        "lat_locality",
        "long_locality",
        "profile_pdf",
        "is_premium_interest",
        "si_event",
        "unapprove_carousel",
        "is_call_back",
        "call_back_query",
        "is_deleted",
        "deleted_by",
        "id_families",
        "relation",
        "livingWithParents",
        "locality",
        "city_family",
        "mobile_family",
        "backup_mobile_family",
        "email_family",
        "unmarried_brothers",
        "married_brothers",
        "unmarried_sisters",
        "married_sisters",
        "family_type",
        "house_type",
        "religion",
        "caste",
        "gotra",
        "occupation_family",
        "family_income",
        "father_status",
        "mother_status",
        "created_at_family",
        "updated_at_family",
        "whatsapp_family",
        "mother_tongue",
        "occupation_mother",
        "address",
        "about_family",
        "father_off_addr",
        "email_verified",
        "genderCode_user",
        "educationCode_user",
        "food_choiceCode",
        "occupationCode_user",
        "manglikCode",
        "maritalStatusCode",
        "casteCode_user",
        "religionCode",
        "houseTypeCode",
        "familyTypeCode",
        "relationCode",
        "profile_percent",
        "created_at_freeUser",
        "updated_at_freeUser",
        "pending_temple_id",
        "welcome_call_done",
        "welcome_call_time",
        "verification_call_done",
        "verifcation_call_time",
        "is_approved",
        "is_approved_on",
        "wishing_to_settle_abroad",
        "approved_by",
        "starvation_score"
    ];
}
